Repository jpmorganchase/sandboni-core, pull requests merged in 2019-10, with the labels that each got.

#35 Bugfix: Finding ignored tests
  engine/pom.xml
  engine/src/main/java/com/sandboni/core/engine/finder/bcel/visitors/Annotations.java
  engine/src/test/java/com/sandboni/core/engine/finder/bcel/BcelFinderTest.java
  engine/src/test/java/com/sandboni/core/engine/scenario/IgnoredClassTest.java
  engine/src/test/java/com/sandboni/core/engine/scenario/PowerMockIgnoreTest.java
  pom.xml
  scm/pom.xml
Labels: bug

#37 Included tests approach
  engine/pom.xml
  engine/src/main/java/com/sandboni/core/engine/Application.java
  engine/src/main/java/com/sandboni/core/engine/Arguments.java
  engine/src/main/java/com/sandboni/core/engine/ArgumentsBuilder.java
  engine/src/main/java/com/sandboni/core/engine/Processor.java
  engine/src/main/java/com/sandboni/core/engine/ProcessorBuilder.java
  engine/src/main/java/com/sandboni/core/engine/ResultGenerator.java
  engine/src/main/java/com/sandboni/core/engine/Stage.java
  engine/src/main/java/com/sandboni/core/engine/SystemProperties.java
  engine/src/main/java/com/sandboni/core/engine/finder/bcel/visitors/SpringMockMvcMethodVisitor.java
  engine/src/main/java/com/sandboni/core/engine/finder/bcel/visitors/TestClassVisitor.java
  engine/src/main/java/com/sandboni/core/engine/finder/bcel/visitors/TestMethodVisitor.java
  engine/src/main/java/com/sandboni/core/engine/result/ResultContent.java
  engine/src/main/java/com/sandboni/core/engine/sta/Context.java
  engine/src/main/java/com/sandboni/core/engine/sta/graph/vertex/CucumberVertex.java
  engine/src/main/java/com/sandboni/core/engine/sta/graph/vertex/TestVertex.java
  engine/src/main/java/com/sandboni/core/engine/sta/operation/CucumberTestsOperation.java
  engine/src/main/java/com/sandboni/core/engine/sta/operation/GraphOperations.java
  engine/src/main/java/com/sandboni/core/engine/sta/operation/IncludedTestOperation.java
  engine/src/main/java/com/sandboni/core/engine/sta/operation/UnitTestsOperation.java
  engine/src/main/java/com/sandboni/core/engine/utils/StringUtil.java
  engine/src/test/java/com/sandboni/core/engine/ApplicationTest.java
  engine/src/test/java/com/sandboni/core/engine/ArgumentBuilderTest.java
  engine/src/test/java/com/sandboni/core/engine/FinderTestBase.java
  engine/src/test/java/com/sandboni/core/engine/ProcessorBuilderTest.java
  engine/src/test/java/com/sandboni/core/engine/ProcessorTest.java
  engine/src/test/java/com/sandboni/core/engine/finder/bcel/BcelFinderTest.java
  engine/src/test/java/com/sandboni/core/engine/render/file/FileWriterEngineTest.java
  engine/src/test/java/com/sandboni/core/engine/result/ResultGeneratorTest.java
  engine/src/test/java/com/sandboni/core/engine/scenario/IncludeTest.java
  engine/src/test/java/com/sandboni/core/engine/scenario/MustRunClassTest.java
  engine/src/test/java/com/sandboni/core/engine/scenario/MustRunMethodTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/BuilderTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/CucumberJavaConnectorTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/HttpTemplateConnectorTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/JiraConnectorTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/JsonConnectorTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/TestConventionConnectorTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/AllExternalTestsOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/AllTestsOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/ChangeStatsOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/CucumberTestsOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/DisconnectedTestsOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/GraphOperationsTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/IncludedTestOperationTest.java
  engine/src/test/java/com/sandboni/core/engine/sta/operation/UnitTestsOperationTest.java
  pom.xml
  scm/pom.xml
Labels: enhancement

#41 Add images for wiki "Design" page
  doc/connectors.png
  doc/finders.png
  doc/sandboni-core.png
  doc/the-core.png
  doc/visitors.png
  engine/pom.xml
  pom.xml
  scm/pom.xml
Labels: documentation
